apiVersion: v1
kind: Service
metadata:
  name: companhia-db-service
  labels:
    app: companhia-db-service
spec:
  type: NodePort  #Alterar após conclusão do projeto
  ports:
    - port: 5432
      nodePort: 30011
  selector:
    app: companhia-db-pod