apiVersion: v1
kind: Service
metadata:
  name: companhia-service
spec:
  type: NodePort  #Alterar após criação do gateway
  selector:
    app: companhia-pod
  ports:
    - port: 9091
      nodePort: 30010