apiVersion: v1
kind: Service
metadata:
  name: companhia-service
  labels:
    app: companhia-service
spec:
  type: NodePort  #Alterar após criação do gateway
  ports:
    - port: 9091
      nodePort: 30010
  selector:
    app: companhia-pod