server:
  servlet:
    context-path: /funcionarios

spring:
  datasource:
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_funcionario?createDatabaseIfNotExist=true&useSSL=false
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect