server:
  port: 8888

spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/RafaelOFreitas/airline-tickets-microservices.git
          search-paths:
            - config-repo/companhia
            - config-repo/funcionario
            - config-repo/voo-command