server:
  port: 8762
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RafaelOFreitas/airline-tickets-microservices.git
          search-paths: microservice-repo/companhia